authentication/urls.py
from django.shortcuts import redirect
from django.urls import path, re_path
from .views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView, logout_then_login
app_name = 'auth'

urlpatterns = [
    path('', redirect_login_view, name="login"),
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path('auth/', redirect_login_view, name="redirect_login"),
    path('logout/', logout_then_login, name="logout"),
    path('password_change/', password_change, name="password_change"),
    
    path('forgot_password/', forgot_password, name="forgot_password"),
    path('forgot_password/reset/<token>/', forgot_password_confirm, name="password_reset_confirm"),
]

coreapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('master/', include('master.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.autodiscover()

master/urls.py
from django.urls import path, include
from . import views

app_name="master"

urlpatterns = [
    path('', views.redirect_to_dashboard, name='homepage'),
    path('dashboard', views.homepage, name='homepage'),
    path('<slug:slug>', views.crud_list, name='crud_list'),
    path('<slug:slug>/list', views.crud_list, name='crud_list'),
    path('<slug:slug>/list/filter', views.filter_crud_list, name='filter_crud_list'),
    path('<slug:slug>/create', views.crud_create_or_update, name='crud_create'),
    path('<slug:slug>/<int:id>/edit', views.crud_create_or_update, name='crud_update'),
    path('<slug:slug>/<int:id>/delete', views.crud_delete, name='crud_delete'),
    path('<slug:slug>/upload', views.upload, name='upload_file'),
]
    

adminlte3/models.py
from django.db import models

# Create your models here.

adminlte3/views.py
from django.shortcuts import render

# Create your views here.

adminlte3/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
        <div class="float-right d-none d-sm-block">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

adminlte3/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
{% load static %}
<nav class="main-header navbar navbar-expand navbar-dark navbar-secondary">
    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link toggle-navbar" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        {% comment %} <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'master:homepage' %}" class="nav-link">Data Master</a>
        </li> {% endcomment %}
        {% comment %} <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">Admin</a>
        </li> {% endcomment %}
    </ul>

    {% block nav_bar_center %}
    <!-- SEARCH FORM -->
    {% comment %} <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form> {% endcomment %}
    {% endblock %}
    {% block nav_custom_menu %}
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            {% block header_dropdowns %}
              <!-- Messages Dropdown Menu -->
              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-comments"></i>
                  <span class="badge badge-danger navbar-badge">3</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Brad Diesel
                          <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">Call me whenever you can...</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user4-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          John Pierce
                          <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">I got your message bro</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                      <img src="{%static 'admin-lte/dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
                      <div class="media-body">
                        <h3 class="dropdown-item-title">
                          Nora Silvester
                          <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                        </h3>
                        <p class="text-sm">The subject goes here</p>
                        <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                      </div>
                    </div>
                    <!-- Message End -->
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                </div>
              </li>
                <!-- Notifications Dropdown Menu -->
              <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                  <i class="far fa-bell"></i>
                  <span class="badge badge-warning navbar-badge">15</span>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <span class="dropdown-item dropdown-header">15 Notifications</span>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                </div>
              </li> {% endcomment %}

            {% block user_info %}

            {% if request.user.is_authenticated %}
              {% if expert_groups %}
              <button type="button" class="btn btn-sm btn-light bg-outline-primary text-dark p-0 px-2 py-1" data-toggle="modal" data-target="#roleSwitchModal"><i class="fas fa-exchange-alt"></i>
                  Role Switcher
              </button>
              {%endif%}
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                  <img src="{%avatar_url 128 %}" class="user-image img-circle elevation-2" alt="User Image">
                  <span class="d-none d-md-inline">{% firstof request.user.get_username %}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                  <!-- User image -->
                  <li class="user-header bg-primary">
                    <img src="{%avatar_url size=160 %}" class="img-circle elevation-2" alt="User Image">

                    <p>
                        {% firstof request.user.get_full_name request.user.get_username %}
                      <small>Member since : {{ request.user.date_joined }}</small>
                    </p>
                  </li>
                 
                  <li class="user-footer">
                    <a href="{% url 'auth:password_change' %}" class="btn btn-default btn-flat">{% trans 'Change Password'%}</a>
                    <a href="{% url 'auth:logout' %}" class="btn btn-default btn-flat float-right">{% trans 'Sign Out'%}<a>
                  </li>
                </ul>
              </li>
            {% endif %}
            {% endblock user_info %}
            {% endblock header_dropdowns %}
        </ul>
    {% endblock nav_custom_menu %} 
     <!-- Control Sidebar -->

{% endblock %}
</nav>

adminlte3/templates/adminlte/lib/_main_sidebar.html
{% load static adminlte_helpers custom_tags %}
    
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar sidebar-dark-primary elevation-4 overflow-auto">
     <!-- Brand Logo -->
    {% block logo %}
        <a href="{% url 'master:homepage' %}" class="brand-link">
            <img src="" alt="" class="brand-image" style="opacity: 1; min-height:40px">
            {% block logo_text %}<span class="brand-text font-weight-bold">Application</span>{% endblock %}
        </a>
    {% endblock %}
    <!-- sidebar: style can be found in sidebar.less -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% avatar_url size=90 %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">{% firstof request.user.get_full_name request.user.username %}</a>
            <a href="#" class="d-block">Role : {{ request.user.groups.first  }}</a>
            
        </div>
      </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <nav class="mt-2" id="sidebar">
            <ul class="nav nav-pills nav-sidebar flex-column nav-compact nav-child-indent text-sm" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a href="{% url 'master:homepage' %}" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i> 
                        <p>Dashboard</p>
                    </a>
                </li>

                <hr style="border:1px solid grey; width:100%">

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-align-justify"></i> <p>Primary Master</p>
                            <p><i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                        
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'country' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>Country</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'province' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>Province</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'district' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>District</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'local_level' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>Local Level</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'fiscal_year' %}" class="nav-link">
                                    <i class="far fa-calendar nav-icon"></i>
                                    <p>Fiscal Year</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'nepali_month' %}" class="nav-link">
                                    <i class="far fa-calendar nav-icon"></i>
                                    <p>Nepali Month</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'gender' %}" class="nav-link">
                                    <i class="fa fa-venus-mars nav-icon"></i>
                                    <p>Gender</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-align-justify"></i> <p>Auth</p>
                            <p><i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'user' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>User</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'group' %}" class="nav-link">
                                    <i class="far fa-compass nav-icon"></i>
                                    <p>Role</p>
                                </a>
                            </li>
                       
                            <li class="nav-item">
                                <a href="{% url 'master:crud_list' 'activity_logs' %}" class="nav-link">
                                    <i class="fa fa-cogs nav-icon"></i>
                                    <p>Activity Log</p>
                                </a>
                            </li>
                        </ul>
                    </li>

            </ul>
        </nav>
        {% endblock nav_links_ul %}
    </div>
    <!-- /.sidebar -->
</aside>

adminlte3/templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

adminlte3/templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

adminlte3/templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'admin-lte/plugins/select2/js/select2.full.min.js' %}"></script>
{% comment %} <script src="{% static 'main/js/fontawesome.min.js' %}"></script> {% endcomment %}


<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>

    $(document).ready(function() {
        // initialize select2 
        $('select#id_student,select#id_program,select#id_supervisor,select#id_research_subject').select2();
        $('.searchselect').select2();

        var path = window.location.pathname;
    
        // Loop through each sidebar link and check if it matches the current URL
        $('ul.nav-sidebar a.nav-link').each(function() {
            var href = $(this).attr('href');
            href = href.replace('/list','')
            // Check if the path starts with the href attribute value
            if (path.includes(href)) {
                $(this).addClass('active');
                
                // If it's a submenu item, expand the parent menu items
                var parentItems = $(this).parents('li.nav-item');
                parentItems.addClass('menu-open');
    
                // Also add 'active' class to parent menu items
                parentItems.children('a.nav-link').addClass('active');
    
                return false; // Exit the loop once a match is found
            }
        });
    });

    function scrollToActiveItem() {
        var activeItem = $('.nav-treeview .nav-link.active');
        if (activeItem.length) {
            var sidebar = $('.main-sidebar');
            var scrollTop = activeItem.offset().top - (sidebar.height() / 2);
            sidebar.animate({scrollTop: scrollTop});
        }
    }

    window.addEventListener('load', scrollToActiveItem);
   
    $.ajaxSetup({
        headers: {
            "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
          }
    });

    $.widget.bridge('uibutton', $.ui.button);
   


    // for navbar toggle, sidebar collapse and show using sidebar state in localstorage
    if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
        $("body").addClass('sidebar-collapse')
    }

    $('.toggle-navbar').click(function() {
        event.preventDefault();
        
        if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
        sessionStorage.setItem("sidebar-toggle-collapsed", "");
        } else {
        sessionStorage.setItem("sidebar-toggle-collapsed", "1");
        }
    
  });


</script>
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %} "></script>


{% block datatable_js %}{% endblock %}

<script src="{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap.min.js' %}"></script>
<script src="{% static 'main/js/noty.js' %}"></script>
<script src="{% static 'main/js/sweetalert.min.js' %}"></script>
<script src="{% static 'main/js/nepali.datepicker.v3.5.min.js' %}"></script>
<script src="{% static 'main/js/jquery-validation.min.js' %}"></script>
<script src="{% static 'main/js/loadingoverlay.min.js' %}"></script>
<script src="{% static 'main/js/bootstrap-waitingfor.min.js' %}"></script>
<script src="{% static 'main/js/custom.js' %}"></script>

{% endblock %}

adminlte3/templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}"> {% endcomment %}
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

<link rel="stylesheet" href="{% static 'main/css/noty.css' %}">
<link rel="stylesheet" href="{% static 'admin-lte/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'main/css/custom.css' %}">
<link rel="stylesheet" href="{% static 'main/css/nepali.datepicker.v3.5.min.css' %}">

{% endblock %}

adminlte3/templates/adminlte/lib/_tab.html
{% load static custom_tags %}

<div class="row mb-2">
    <div class="col-md-12">
        <ul class="nav nav-tabs flex-column flex-sm-row mt-2" id="myTab" role="tablist">
            {% for link in links %}
                {% if link.href == request.path_info %}
                    {% with activeClass="active" %}
                    <li role="presentation" class="nav-item border border-white">
                        <a class="nav-link tab-link active {{ activeClass }} p-1 pr-2 pl-2" 
                        href="{{ link.href }}" role="tab">{{ link.label }}</a>
                    </li>
                    {%endwith%}
                {% else %}
                    <li role="presentation" class="nav-item border border-white">
                        <a class="nav-link tab-link bg-lightblue text-white  p-1 pr-2 pl-2" 
                        href="{{ link.href }}" role="tab">{{ link.label }}</a>
                    </li>
                {%endif%}
            {% endfor %}
        </ul>
    </div>
</div>
<hr style="border:1px solid lightgray; width:100%">
  
<style>
    .nav-tabs .nav-link.active{
      color:#da4040 !important;
      font-weight:550 !important;
      border-color: rgba(241, 241, 241, 0.66) !important;
      border-bottom: 3px solid #467fcf !important;
    }
  </style>