coreapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('master/', include('master.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.autodiscover()

master/urls.py
from django.urls import path, include
from . import views

app_name="master"

urlpatterns = [
    path('', views.redirect_to_dashboard, name='homepage'),
    path('dashboard', views.homepage, name='homepage'),
    path('<slug:slug>', views.crud_list, name='crud_list'),
    path('<slug:slug>/list', views.crud_list, name='crud_list'),
    path('<slug:slug>/list/filter', views.filter_crud_list, name='filter_crud_list'),
    path('<slug:slug>/create', views.crud_create_or_update, name='crud_create'),
    path('<slug:slug>/<int:id>/edit', views.crud_create_or_update, name='crud_update'),
    path('<slug:slug>/<int:id>/delete', views.crud_delete, name='crud_delete'),
    path('<slug:slug>/upload', views.upload, name='upload_file'),
]
    

master/models.py
from django.db import models
from django.contrib.gis.db import models as gis_modals
from .BaseModels import BaseModel
from django.core.validators import EmailValidator
from .validators import *


class Country(BaseModel):
    boundary = gis_modals.MultiPolygonField(null=True)
    apiid = models.CharField(max_length=50, null=True)
    
    class Meta:
        db_table = 'mst_countries'


class Province(BaseModel):
    apiid = models.CharField(max_length=50, null=True)
    gps_lat = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    gps_long = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    boundary = gis_modals.MultiPolygonField(null=True)

    class Meta:
        db_table = 'mst_provinces'
        ordering = ['display_order']


class District(BaseModel):
    province_id = models.ForeignKey(Province, on_delete=models.PROTECT)
    apiid = models.CharField(max_length=50, null=True)
    gps_lat = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    gps_long = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    boundary = gis_modals.MultiPolygonField(null=True)

    class Meta:
        db_table = 'mst_districts'
        ordering = ['display_order']

class LocalLevel(BaseModel):
    district_id = models.ForeignKey(District, on_delete=models.PROTECT)
    apiid = models.CharField(max_length=50, null=True)
    wards_count = models.IntegerField(null=True)
    gps_lat = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    gps_long = models.DecimalField(max_digits=10, decimal_places=7, null=True)
    boundary = gis_modals.MultiPolygonField(null=True)

    class Meta:
        db_table = 'mst_local_levels'
        ordering = ['code']


class FiscalYear(models.Model):
    code = models.CharField(max_length=7)
    from_date_bs = models.CharField(max_length=10)
    from_date_ad = models.DateField()
    to_date_bs = models.CharField(max_length=10)
    to_date_ad = models.DateField()
    is_active = models.BooleanField(default=True)
    display_order = models.IntegerField(null=True)
    created_at = models.DateTimeField(
        auto_now_add=True, editable=False, null=False, blank=False)
    updated_at = models.DateTimeField(
        auto_now=True, editable=False, null=False, blank=False)

    class Meta:
        db_table = 'mst_fiscal_years'
        ordering = ['display_order']
        
    def __str__(self):
        return "%s" %(self.code)
        
class NepaliMonth(BaseModel):
    class Meta:
        db_table = 'mst_nepali_months'
        
class Gender(BaseModel):
    class Meta:
        db_table = 'mst_genders'
        

master/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseBadRequest, JsonResponse
from django.shortcuts import redirect, render
from django.db import transaction,IntegrityError
from django.db.models import Count,Subquery,OuterRef
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from authentication.models import *
from .filters import *
from .forms import *
from .models import *
from .templatetags.custom_tags import *
from django.core.paginator import Paginator
import json,re,math,traceback,pandas as pd


global import_models
import_models = []
allowed_app_labels=['master','auth','authentication']


@login_required
def homepage(request):
    
    context = {
    
    }
    return render(request, 'layouts/dashboard.html',context)

@login_required
def redirect_to_dashboard(request):
    return redirect('/master/dashboard')


# List Operation
@login_required
def crud_list(request,slug,pid=''):
    # get model name from slug
    model = _to_pascalcase(slug)
    category = ''
     # first check for permission
    if(check_permission(request.user,('view',slug)) is False):
        return render(request,"adminlte/pages/error/403page.html")
    
    # pass page header name
    header = re.sub(r"(\w)([A-Z])", r"\1 \2", model)
    filterFields = ''

    # check if filter class is present or not
    try:
        filterClass = eval(model+'Filter')
    except NameError:
        filterClass = ''

    if filterClass:
        filterFields = filterClass(request.GET, queryset=eval(model).objects.all(),request=request)
        
    if model in import_models:
        upload_button = True
    else:
        upload_button = False
    
    tab_links= ''
    # check for tab
          
    # show filter-section only if filters are available
    hasFilter = False
    if filterFields != '' and filterFields._meta.fields:
        hasFilter = True
            
    page_num = request.GET.get('page',None)
    if page_num is not None:
        page_num = page_num
    else:
        page_num=1     
    context = {'header': header, 'slug': slug, 'hasFilter': hasFilter,'page_num':page_num,
               'filterFields': filterFields, 'upload_button': upload_button,
    }
    return render(request, "adminlte/pages/list.html", context)


# Render List Operation partial view
@login_required
def filter_crud_list(request, slug):
    modelForm = ''
    columns = ''
    labels = ''
     # first check for permission
    if(check_permission(request.user,('view',slug)) is False):
        return render(request,"adminlte/pages/error/403page.html")
    
    # check for filter class; if filter class is present return lists as queryset else return list
    hasFilterClass=False
    removeFilter= False
     ##get page num
    page_num = request.GET.get('page',None)
    
    # get model name from slug
    model = _to_pascalcase(slug)
    # buid form from model
    try:
        modelForm = eval(model+'Form')
    except NameError:
        modelForm = ''

    #allow adding elements to the table
    # get columns name and label  for list operation
    if modelForm != '':
        columns = modelForm._meta.fields
        #custom change for removing many-to-many ralation field 
        labels = modelForm._meta.labels
    # get all data from table
    lists = eval(model).objects.all()
    
    if model == 'Group':
        lists = lists.order_by('id')
    
    if request.GET is not None:
        # if filter is present
        filterClass=''
        try:
            filterClass = eval(model+'Filter')
        except NameError:
            filterClass = ''

        if filterClass != '': 
            page_param = request.GET.get('page',None)
            modified_request = request.GET.copy()
            if page_param:
                del modified_request['page']
                
            lists = filterClass(modified_request, queryset=lists)
            hasFilterClass= True
            
        try :
            exclude_lists = modelForm.exclude_on_lists() 
        except Exception as e:
            exclude_lists = ('name_lc',) 
        try :
            include_lists = modelForm.include_on_lists()
        except Exception as e:
            include_lists = '' 
    #To remove columns if they are not needed in list       
    if exclude_lists:
        original_columns = columns
        new_columns = tuple(x for x in original_columns if x not in exclude_lists)
        columns = new_columns
    
    if include_lists:
        columns= columns + include_lists
        
    #pagination
    if(filterClass):
        lists = Paginator(lists.qs,20)
    else:
        lists=Paginator(lists,20)    
    list_count = lists.count
 
    if page_num is not None:
        lists = lists.page(page_num)
    else:
        lists=lists.page(1)    
    
    context = {'columns': columns, 'labels': labels,'hasFilterClass':hasFilterClass,
               'lists': lists,'lists_count':list_count, 'slug': slug,'model':model, }
    return render(request, "adminlte/pages/partial/datatable.html", context)

# Create or Update Operation
@login_required
def crud_create_or_update(request, slug,id=0):
    model = _to_pascalcase(slug)
    header = re.sub(r"(\w)([A-Z])", r"\1 \2", model)
    if slug == 'exam_application':
        header='Research Examination Application'  
    modelForm = model+'Form'
    permissions = ''
    content_types = ''
    group_permission = ''
    user = request.user
    
    if request.method == "GET":
        if id == 0:
            # first check for permission
            if(check_permission(request.user,('add',slug)) is False):
                return render(request,"adminlte/pages/error/403page.html")
            form = eval(modelForm)(user)
            permissions = Permission.objects.filter(content_type__app_label__in=allowed_app_labels)
            content_types = ContentType.objects.filter(app_label__in=allowed_app_labels)
    
            context={
                'form':form,
                'slug':slug,
                'header':header,
                'permissions':permissions,
                'content_types':content_types,
            }
            return render(request, "adminlte/pages/create.html", context)
        else:
            # first check for permission
            if(check_permission(request.user,('change',slug)) is False):
                return render(request,"adminlte/pages/error/403page.html")
            
            entity = eval(model).objects.get(pk=id)
            
            if slug == 'user':
                form = UserEditForm(user,instance=entity)
            else:    
                form = eval(modelForm)(user,instance=entity)
               
            if slug == 'group':
                permissions = Permission.objects.filter(content_type__app_label__in=allowed_app_labels)
                content_types = ContentType.objects.filter(app_label__in=allowed_app_labels)
                
                group_permission = Group.objects.get(pk=id)
                group_permission = group_permission.permissions.filter(id__in=permissions).values_list('id')
                group_permission = [item[0] for item in group_permission]
    
            context={
                'form':form,
                'slug':slug,
                'header':header,
                'entry': entity,
                'permissions':permissions,
                'content_types':content_types,
                'permissions':permissions,
                'content_types':content_types,
                'group_permission':group_permission,
            }
            return render(request, "adminlte/pages/edit.html", context)
    else:
        message = ''
        status ='success'
        if id == 0:
            # first check for permission
            if(check_permission(request.user,('add',slug)) is False):
                return render(request,"adminlte/pages/error/403page.html")
            form = eval(modelForm)(user,request.POST, request.FILES)
        else:
            # first check for permission
            if(check_permission(request.user,('change',slug)) is False):
                return render(request,"adminlte/pages/error/403page.html")
            entity = eval(model).objects.get(pk=id)
            
            if slug == 'user':
                form = UserEditForm(user,request.POST, request.FILES, instance=entity)
            else:
                form = eval(modelForm)(user,request.POST, request.FILES, instance=entity)

        if form.is_valid():
            form.save()
            if slug == 'user':
                user_id = form.instance.id
                create_user_role(request,user_id)
                
            if slug == 'group':
                group_id = form.instance.id
                create_group_permission(request,group_id)
            
            if id == 0:
                message = 'The item has been added successfully !'
            else:
                message = 'The item has been modified successfully !'
        else:
            status = 'fail'
            message = form.errors.as_json()
        return JsonResponse({'status':status,'message': message, 'slug': slug})
    
@login_required
def crud_delete(request, slug, id):
    # first check for permission
    if(check_permission(request.user,('delete',slug)) is False):
        return render(request,"adminlte/pages/error/403page.html")
    model = _to_pascalcase(slug)
    entity = eval(model).objects.get(pk=id)
    delete_status = entity.delete()
    if(delete_status):
        status = 'success'
        value = 1
    else:
        status = 'error'
        value = 0
    return JsonResponse({'status': status, 'value': value, 'slug': slug})


def _to_pascalcase(value):
    output = ""
    first_word_passed = False
    for word in value.split("_"):
        if not word:
            output += "_"
            continue
        if first_word_passed:
            output += word.capitalize()
        else:

master/templates/custom_fields/map_field.html
{% load static %}

    <!--Stylesheets-->
      <link rel="stylesheet" type="text/css" href="{% static 'main/leaflet/leaflet.css' %}" />
    <style>
        #map {
            border: 1px solid gray;
            border-radius: 25px;
            margin:25px 2% 50px 25%;
            height:calc(100vh - 300px);
            width: calc(100vh + 200px);
        }

        @media screen and (min-width: 1000px) and (max-width:1700px){
            #map {
                  border: 1px solid gray;
                  border-radius: 25px;
                  margin:25px 2% 50px 10%;
                  height:calc(100vh - 200px);
                  width: calc(100vh + 400px);
                  }
        }
    
    </style>
<div class="row">
      <div class ="col-md-10"id='map'></div>
</div>
<script type="text/javascript"  src="{% static 'main/leaflet/leaflet.js' %}" ></script>
<script type="text/javascript"  src="{% static 'main/leaflet/leaflet.js.map' %}" ></script>

 <script>
      var mbAttr = 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
            '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
            'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            mbUrl = 'http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}';

            var satellite = L.tileLayer(mbUrl, {
                  id: 'mapbox.streets-satellite',
                  attribution: mbAttr,
                  maxZoom: 20,
                  subdomains:['mt0','mt1','mt2','mt3']
            });
          

      var map = L.map('map', {
            center: [28.34, 84.25],
            zoom: 7.0,
            layers: [satellite],
      });

      var baseLayers = {
            "Satellite": satellite,
      };

      L.control.layers(baseLayers).addTo(map);

      var display_icon = L.icon({iconUrl:'/static/main/leaflet/images/marker-icon.png',iconSize:[20,30]})
      var marker = L.marker( [0, 0],{icon:display_icon}).addTo(map);
      
            map.on('click', function(e) {
            let latitude = e.latlng.lat.toString().substring(0, 8);
            let longitude = e.latlng.lng.toString().substring(0, 8);
            $('#id_gps_lat').val(latitude);
            $('#id_gps_long').val(longitude);

            updateMarker(latitude, longitude);
            });

            function updateMarker(lat, lng) {
            marker
            .setLatLng([lat, lng])
            .bindPopup("Coordinates :  " + marker.getLatLng().toString())
            .openPopup();
            map.setView([lat,lng],20);
            $('#id_gps_lat').val(lat);
            $('#id_gps_long').val(lng);
            return false;
            };


            function updateMarkerByInputs() {
            var latitude = $('#id_gps_lat').val();
            var longitude = $('#id_gps_long').val();
            return updateMarker(latitude,longitude);
            }


      function getLocation() {
            if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
            } else {
                  alert("Your Browser does not support Geo-location.");
            }
      }

      function showPosition(position) {
            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
            updateMarker(latitude, longitude);
      }

      $('#id_gps_lat').change(function(){
            updateMarkerByInputs();
      });
      $('#id_gps_long').change(function(){
            updateMarkerByInputs();
      });

      if($('#id_gps_lat').val() =='')
      {
            getLocation();
      }else{
            updateMarkerByInputs();
      }

</script>

master/templates/custom_fields/toggle.html
<div>
    <input class="toggle-checkbox" type="checkbox" checked name="{{ widget.name }}"{% if widget.value != None %} value="{{ widget.value|stringformat:'s' }}"{% endif %}{% include "django/forms/widgets/attrs.html" %}>
    <div class="toggle-switch"></div>
</div>