authentication/urls.py
from django.shortcuts import redirect
from django.urls import path, re_path
from .views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView, logout_then_login
app_name = 'auth'

urlpatterns = [
    path('', redirect_login_view, name="login"),
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path('auth/', redirect_login_view, name="redirect_login"),
    path('logout/', logout_then_login, name="logout"),
    path('password_change/', password_change, name="password_change"),
    
    path('forgot_password/', forgot_password, name="forgot_password"),
    path('forgot_password/reset/<token>/', forgot_password_confirm, name="password_reset_confirm"),
]

coreapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('master/', include('master.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
admin.autodiscover()

master/urls.py
from django.urls import path, include
from . import views

app_name="master"

urlpatterns = [
    path('', views.redirect_to_dashboard, name='homepage'),
    path('dashboard', views.homepage, name='homepage'),
    path('<slug:slug>', views.crud_list, name='crud_list'),
    path('<slug:slug>/list', views.crud_list, name='crud_list'),
    path('<slug:slug>/list/filter', views.filter_crud_list, name='filter_crud_list'),
    path('<slug:slug>/create', views.crud_create_or_update, name='crud_create'),
    path('<slug:slug>/<int:id>/edit', views.crud_create_or_update, name='crud_update'),
    path('<slug:slug>/<int:id>/delete', views.crud_delete, name='crud_delete'),
    path('<slug:slug>/upload', views.upload, name='upload_file'),
]
    

authentication/models.py
from django.db import models,connection
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from rest_framework.authtoken.models import Token
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.signals import user_logged_in, user_login_failed

class User(AbstractUser):
    # add additional fields here
    token=models.CharField(max_length=50,null=True,blank=True)
    is_password_changed = models.BooleanField(default=False)
    current_group_id = models.IntegerField(blank=True,null=True)
    last_activity = models.DateTimeField(
        _('last activity'), default=timezone.now, editable=False)

    
    def __str__(self):
        return self.username

    def update_last_activity(self):
        self.last_activity = timezone.now()
        self.save(update_fields=["last_activity"])
    
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

def get_client_ip(request):
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    return (
        x_forwarded_for.split(",")[0]
        if x_forwarded_for
        else request.META.get("REMOTE_ADDR")
    )



CREATE, READ, UPDATE, DELETE = "Create", "Read", "Update", "Delete"
LOGIN, LOGOUT, LOGIN_FAILED = "Login", "Logout", "Login Failed"
ACTION_TYPES = [
    (CREATE, CREATE),
    (READ, READ),
    (UPDATE, UPDATE),
    (DELETE, DELETE),
    (LOGIN, LOGIN),
    (LOGOUT, LOGOUT),
    (LOGIN_FAILED, LOGIN_FAILED),
]

SUCCESS, FAILED = "Success", "Failed"
ACTION_STATUS = [(SUCCESS, SUCCESS), (FAILED, FAILED)]


@receiver(user_logged_in)
def log_user_login(sender, request, user, **kwargs):
    message = f"{user.username} is logged in with ip:{get_client_ip(request)}"
    ActivityLogs.objects.create(actor=user, action_type=LOGIN, extra_data=message)


@receiver(user_login_failed)
def log_user_login_failed(sender, credentials, request, **kwargs):
    message = f"Login Attempt Failed for username: {credentials.get('username')} with ip: {get_client_ip(request)}"
    ActivityLogs.objects.create(action_type=LOGIN_FAILED, extra_data=message)
    
class ActivityLogs(models.Model):
    actor = models.ForeignKey(User,models.SET_NULL,null=True,blank=True)
    request_url = models.CharField(_('url'), max_length=256,null=True,blank=True)
    request_method = models.CharField(_('http method'), max_length=10, db_index=True,null=True,blank=True)
    response_code = models.CharField(_('response code'), max_length=3, db_index=True,null=True,blank=True)
    action_type = models.CharField(choices=ACTION_TYPES, max_length=15)
    datetime = models.DateTimeField(_('datetime'), default=timezone.now, db_index=True)
    status = models.CharField(choices=ACTION_STATUS, max_length=7, default=SUCCESS)
    extra_data = models.JSONField(default=dict)
    ip_address = models.GenericIPAddressField(_('user IP'), null=True, blank=True, db_index=True)
    model = models.CharField(max_length=50,blank=True, null=True)
    class Meta:
        db_table = 'activity_logs'

    def __str__(self) -> str:
        return f"{self.action_type} by {self.actor} on {self.datetime}"

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from coreapp.settings import AUTH_USER_MODEL


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "First Name",
                "class": "form-control"
            }
        ))
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Last Name",
                "class": "form-control"
            }
        ))
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password confirmation",
                "class": "form-control",
            }
        ))

    class Meta:
        model = get_user_model()

        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2')

authentication/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from authentication.models import User
from django.contrib import messages
from .forms import LoginForm, SignUpForm
from django.contrib.auth.hashers import make_password
from django.utils.decorators import decorator_from_middleware
from .middleware import *
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import send_mail,EmailMessage,BadHeaderError
import secrets

# Define a decorator that excludes the middleware
exclude_middleware = decorator_from_middleware(PasswordChangeMiddleware)

@exclude_middleware
def redirect_login_view(request):
    return redirect('auth:login')

@exclude_middleware
def login_view(request):
    if request.user.is_authenticated :
        # Get the 'next' parameter from the query string
        next_url = request.GET.get('next', '/master/')
        return redirect(next_url)
     
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            # check if the username exist in database
            try:
                User.objects.get(username=username)
            except:
                messages.error(request,'Username does not exist')

            # check the credential
            user = authenticate(request,username=username,password=password)

            if user is not None:
                login(request, user)
                # Get the 'next' parameter from the query string
                next_url = request.POST.get('next', '/master/')
                return redirect(next_url)
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def register_user(request):

    msg = None
    success = False
    print(request.POST)
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            msg = 'New user registered successfully !!'
            success = True
            # redirect to login view if user is registered
            return render(request, "accounts/register.html", {"form": SignUpForm(), "msg": msg,"status":success})

        else:
            msg = form.errors
            return render(request, "accounts/register.html", {"form": SignUpForm(), "msg": msg,"status":success})
    else:
        form = SignUpForm()

        return render(request, "accounts/register.html", {"form": SignUpForm(), "msg": msg,"status":success})


def password_change(request):
    if request.user.is_authenticated is False:
         return redirect("auth:login")
     
    if request.method == 'GET':
        return render(request, "accounts/password-change.html")
    
    else:
        msg=''
        # check if the username exist in database
        try:
            password1= request.POST.get('password')
            password2= request.POST.get('confirm_password')
            if password1 == password2:
                User.objects.filter(username=request.user).update(password=make_password(password1),is_password_changed=True)
                msg = 'Password Changed Successfully !!'
                return redirect('auth:logout')
            else:
                msg="Password doesn't match !!"    
            
        except Exception as e:
            print(e)
            msg ='Something is wrong !!'

    return render(request, "accounts/password-change.html", {"msg": msg})

@exclude_middleware
def forgot_password(request):
     
    if request.method == 'GET':
        return render(request, "accounts/forgot-password.html")
    else:
        msg=''
        # check if the username exist in database
        try:
            username= request.POST.get('username')
            user = User.objects.get(username=username)
            
            if user and user.email:
                subject = 'Applicaiton-Password Reset Link'
                from_email='test@gmail.com'
                
                recipient_list=[user.email]

                base_url = settings.BASE_URL
                
                token = secrets.token_hex(50 // 2)
                user.token = token
                user.save()
                message=''
                context ={
                    'user':user,
                    'base_url':base_url,
                    'token':token,
                }
                # Render the email content from the template
                email_content = render_to_string('email/password_reset_email.html', context)
                try:
                    
                    email = EmailMessage(subject, email_content, from_email, recipient_list)
                    email.content_subtype='html'
                    email.send()
                    msg = 'Password Reset Link sent on registered email !!'
                except BadHeaderError:
                    msg="Invalid header found in email."
                except Exception as e:
                    # Handle other exceptions (e.g., SMTP errors) here
                    msg = 'Error Occured !!'
                return redirect('auth:login')
            else:
                msg="Either Username doesn't match or E-mail is not configured !! Please Contact Administrator."    
            
        except Exception as e:
            print(e)
            msg =e

            return render(request, "accounts/forgot-password.html", {"msg": msg})
        
@exclude_middleware        
def forgot_password_confirm(request,token):
    user = User.objects.filter(token=token)
    if user.exists():
        user = user.first()
        if request.method == 'GET':
            context={
                'user':user,
            }
            return render(request,'accounts/password_reset_confirm.html',context)
        else:
            try:
                password1= request.POST.get('password')
                password2= request.POST.get('confirm_password')
                if password1 == password2:
                    user.password=make_password(password1)
                    user.is_password_changed=True
                    user.token=''
                    user.save()
                    
                    msg = 'Password Changed Successfully !!'
                    return redirect('auth:logout')
                else:
                    msg="Password doesn't match !!"    
                
            except Exception as e:
                print(e)
                msg ='Something is wrong !!'
            return render(request, "accounts/password_reset_confirm.html", {"msg": msg})
    else:
        msg="Token Expired !! Please Create New Request !!"
        return render(request, "accounts/forgot-password.html", {"msg": msg})
   
   
             

authentication/templates/accounts/forgot-password.html
{% extends 'adminlte/base.html' %}
{% load i18n static %}

{% block body_class %}
  login-page
{% endblock %}

{% block body %}
  <div class="login-box">
    <div class="card card-outline card-primary">
      <div class="card-header text-center">
        <h5 class="font-weight-bold">Password reset</h5>
      </div>
      <div class="card-body">
        <p class="login-box-msg">
            Forgotten your password?<br/> Enter your username below, and we’ll email instructions for setting a new one.<br></p>
        <form action="{% url 'auth:forgot_password' %}" method="post">

          {% csrf_token %}
                        
          {% block login_errors %}
            {% if msg %}
                    <p class="errorlist">Error : {{ msg }}</p>
            {% endif %}
            {% endblock login_errors %}
          <div class="input-group mb-4 mt-4">
            <input type="text" name="username" class="form-control username" placeholder="Username..." required />
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-user"></span>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-12 text-center">
              <button type="submit" class="btn btn-primary btn-block">Submit</button>
              <a href="/" class="btn btn-sm btn-block btn-secondary mt-2" role="button">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

authentication/templates/accounts/login.html
{% extends "adminlte/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
    <div class="login-box">
        {% block logo %}
          <div class="login-logo pr-5">
            {% block logo_text %}<span class="font-weight-normal text-dark">Application</span>{% endblock %}
          </div>
        {% endblock %}
        <!-- /.login-logo -->
      <div class="card">
            <div class="card-body login-card-body">

                <p class="login-box-msg text-dark font-weight-bold">Sign in to start your session</p>
                {% block login_form %}
                    <form action="{% url 'auth:login' %}" method="post">
                        {% csrf_token %}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        {% block login_errors %}

                        {% if msg %}
                              <p class="errorlist">Error : {{ msg }}</p>
                        {% endif %}
                      {% endblock login_errors %}

                        <div class="input-group mb-3 mt-3">
                          {{ form.username }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-user"></span>
                            </div>
                          </div>
                        </div>
                        <div class="input-group mb-3">
                          {{ form.password }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-lock"></span>
                            </div>
                          </div>
                        </div>
                        <div class="row ml-2">
                            <div class="check-primary">
                              <div class="col-md-12 mb-2">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="toggle" id="toggle">
                                    <label class="form-check-label" for="toggle">Show Password</label>
                                </div>
                            </div>
                            </div>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary btn-block">{% trans 'Sign In' %}</button>
                        </div>
                    </form>
                {% endblock login_form %}
   
                
                <!-- /.social-auth-links -->
                <div class=" text-center mt-3">

                    <p class="mb-0 font-weight-bold">
                      New user ?? <a href="{% url 'auth:register' %}" class="text-center ml-2"> Register Here !</a>
                    </p>
                    <p class="mb-0">
                      <a href="{% url 'auth:forgot_password' %}" class="text-center"> Forgot password !! </a>
                    </p>
                </div>

            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
{% endblock %}

{% block js %}
<script type="text/javascript">
$('#toggle').click(function(){
  var input = document.getElementById("id_password");
  if (input.type === "password") {
    input.type = "text";
  } else {
    input.type = "password";
  }
});
</script>
{% endblock %}

authentication/templates/accounts/password-change.html
{% extends 'adminlte/base.html' %}
{% load i18n static %}

{% block body_class %}
  login-page
{% endblock %}

{% block body %}
  <div class="login-box">
    <div class="card card-outline card-primary">
      <div class="card-header text-center">
        <h5 class="font-weight-bold">Change Password</h5>
      </div>
      <div class="card-body">
        <p class="login-box-msg">
        {% if request.user.is_password_changed %}
          Change your account password !!
        {%else%}
          You have not changed your default password.<br><span class="text-danger"> Please, change your password first !!.</span></p>
          {%endif%}
        <form action="{% url 'auth:password_change' %}" method="post">

          {% csrf_token %}
                        
          {% block login_errors %}

          {% if msg %}
                <p class="errorlist">Error : {{ msg }}</p>
          {% endif %}
        {% endblock login_errors %}
          <div class="input-group mb-3">
            <input type="password" name="password" class="form-control password" placeholder="Password" required />
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <input type="password" name="confirm_password" class="form-control password" placeholder="Confirm Password" required />
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>

          <div class="row ml-2">
            <div class="check-primary">
              <div class="col-md-12 mb-2">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="toggle" id="toggle">
                    <label class="form-check-label" for="toggle">Show Password</label>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 text-center">
              <button type="submit" class="btn btn-primary btn-block">Change password</button>
              <a href="/" class="btn btn-sm btn-block btn-secondary mt-2" role="button">Cancel</a>
            </div>
          </div>
        </form>
        <p class="mt-3 mb-1 text-center">
        </p>
      </div>
    </div>
  </div>
  <!-- /.login-box -->
{% endblock %}

{% block js %}
  <script type="text/javascript">
    $('#toggle').click(function () {
      var input = document.getElementsByClassName('password')

      $.each(input,function(index,itm){
        if (itm.type === 'password') {
          itm.type = 'text'
        } else {
          itm.type = 'password'
        }
      })
    
    })
  </script>
{% endblock %}

authentication/templates/accounts/password_reset_confirm.html
{% extends 'adminlte/base.html' %}
{% load i18n static %}

{% block body_class %}
  login-page
{% endblock %}

{% block body %}
  <div class="login-box">
    <div class="card card-outline card-primary">
      <div class="card-header text-center">
        <h5 class="font-weight-bold">Password Reset Confirmation</h5>
      </div>
      <div class="card-body">
        <p class="login-box-msg mb-2">
            Please enter your new password twice so we can verify you typed it in correctly.<br></p>
        <form method="post">

          {% csrf_token %}
                        
          {% block login_errors %}

          {% if msg %}
                <p class="errorlist">Error : {{ msg }}</p>
          {% endif %}
        {% endblock login_errors %}
          <div class="input-group mb-3">
            <input type="password" name="password" class="form-control password" placeholder="Password" required />
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <input type="password" name="confirm_password" class="form-control password" placeholder="Confirm Password" required />
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-lock"></span>
              </div>
            </div>
          </div>

          <div class="row ml-2">
            <div class="check-primary">
              <div class="col-md-12 mb-2">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="toggle" id="toggle">
                    <label class="form-check-label" for="toggle">Show Password</label>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 text-center">
              <button type="submit" class="btn btn-primary btn-block">Change password</button>
              <a href="/" class="btn btn-sm btn-block btn-secondary mt-2" role="button">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block js %}
  <script type="text/javascript">
    $('#toggle').click(function () {
      var input = document.getElementsByClassName('password')

      $.each(input,function(index,itm){
        if (itm.type === 'password') {
          itm.type = 'text'
        } else {
          itm.type = 'password'
        }
      })
    
    })
  </script>
{% endblock %}

authentication/templates/accounts/register.html
{% extends "adminlte/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
    <div class="login-box" style="width:500px">
        {% block logo %}
        <div class="login-logo pr-5">
          {% comment %} <img src="{%static 'main/img/gas_header.png' %}" alt="Logo" style="height:50px"> {% endcomment %}
          {% block logo_text %}<span class="font-weight-normal text-dark">Track My Thesis</span>{% endblock %}
        </div>
        {% endblock %}
      <div class="card">
            <div class="card-body login-card-body">

                <p class="login-box-msg text-dark font-weight-bold">Register as new user !!</p>
                {% block register_form %}
                    <form action="" method="post">
                        {% csrf_token %}

                          {% block login_errors %}
                              {% if form.errors %}
                                  {% for field,error in msg.items %}
                                     {{ error }}
                                  {% endfor %}
                              {% endif %}
                            {% endblock login_errors %}

                        <div class="row mt-3">
                          <div class="col input-group mb-3">
                            {{ form.first_name }}
                            <div class="input-group-append">
                              <div class="input-group-text">
                                <span class="fas fa-pen"></span>
                              </div>
                            </div>
                          </div>
                          <div class="col  input-group mb-3">
                            {{ form.last_name }}
                            <div class="input-group-append">
                              <div class="input-group-text">
                                <span class="fas fa-pen"></span>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div class="input-group mb-3">
                          {{ form.username }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-user"></span>
                            </div>
                          </div>
                        </div>
                        <div class="input-group mb-3">
                          {{ form.email }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-envelope"></span>
                            </div>
                          </div>
                        </div>
                        <div class="input-group mb-3">
                          {{ form.password1 }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-lock"></span>
                            </div>
                          </div>
                        </div>
                        <div class="input-group mb-3">
                          {{ form.password2 }}
                          <div class="input-group-append">
                            <div class="input-group-text">
                              <span class="fas fa-lock"></span>
                            </div>
                          </div>
                        </div>
                        
                        <div class="row">
                            <button type="submit" class="btn btn-primary btn-block">{% trans 'Register' %}</button>
                        </div>
                    </form>
                {% endblock register_form %}
                
                <div class=" text-center mt-3 font-weight-bold">
                  <p class="mb-0">
                      Already a registered user ??<a href="{% url 'auth:login' %}" class="text-center"> Sign in here !!</a>
                  </p>
                </div> 
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
{% endblock %}

{% block js %}
<script type="text/javascript">
  let status = "{{status}}";
  if(status == 'True'){

    new Noty({
      type: 'success',
      text: '{{msg}}',
      timeout: 2000,
      progressBar:true,
      closeWith:['click'],
    }).show()

    setTimeout(function(){
      window.location.href ="/login/";
    },2500)
     
  }
</script>
{% endblock %}